platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'DemoLightbox' do
  pod 'Lightbox', path: '../../'
  pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar', branch: 'swift-3'
  pod 'Hue', git: 'https://github.com/hyperoslo/Hue', branch: 'swift3'
end
